"""initiate

Revision ID: 9266e94d5467
Revises: 
Create Date: 2024-05-09 16:02:15.099241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9266e94d5467'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_a', sa.String(length=3), nullable=True),
    sa.Column('team_b', sa.String(length=3), nullable=True),
    sa.Column('stage', sa.String(length=17), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('score_a', sa.Integer(), nullable=True),
    sa.Column('score_b', sa.Integer(), nullable=True),
    sa.Column('first_goal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_stage'), 'game', ['stage'], unique=False)
    op.create_index(op.f('ix_game_starts_at'), 'game', ['starts_at'], unique=False)
    op.create_index(op.f('ix_game_team_a'), 'game', ['team_a'], unique=False)
    op.create_index(op.f('ix_game_team_b'), 'game', ['team_b'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('default_score_a', sa.Integer(), nullable=True),
    sa.Column('default_score_b', sa.Integer(), nullable=True),
    sa.Column('default_first_goal', sa.Integer(), nullable=True),
    sa.Column('final_winner', sa.String(length=3), nullable=True),
    sa.Column('final_winner_timestamp', sa.DateTime(), nullable=True),
    sa.Column('final_winner_points', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('total_score_diff', sa.Integer(), nullable=True),
    sa.Column('total_winner', sa.Integer(), nullable=True),
    sa.Column('total_first_goal', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('total_closed_bets', sa.Integer(), nullable=True),
    sa.Column('overall_points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_final_winner_timestamp'), 'user', ['final_winner_timestamp'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('winnerbet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('last_bet', sa.DateTime(), nullable=True),
    sa.Column('bet_points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_winnerbet_last_bet'), 'winnerbet', ['last_bet'], unique=False)
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('score_a', sa.Integer(), nullable=True),
    sa.Column('score_b', sa.Integer(), nullable=True),
    sa.Column('first_goal', sa.Integer(), nullable=True),
    sa.Column('is_default_bet', sa.Boolean(), nullable=True),
    sa.Column('first_goal_correct', sa.Boolean(), nullable=True),
    sa.Column('winner_correct', sa.Boolean(), nullable=True),
    sa.Column('score_diff_correct', sa.Boolean(), nullable=True),
    sa.Column('score_correct', sa.Boolean(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_game_id'), 'bet', ['game_id'], unique=False)
    op.create_index(op.f('ix_bet_timestamp'), 'bet', ['timestamp'], unique=False)
    op.create_index(op.f('ix_bet_user_id'), 'bet', ['user_id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_bet_user_id'), table_name='bet')
    op.drop_index(op.f('ix_bet_timestamp'), table_name='bet')
    op.drop_index(op.f('ix_bet_game_id'), table_name='bet')
    op.drop_table('bet')
    op.drop_index(op.f('ix_winnerbet_last_bet'), table_name='winnerbet')
    op.drop_table('winnerbet')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_final_winner_timestamp'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_game_team_b'), table_name='game')
    op.drop_index(op.f('ix_game_team_a'), table_name='game')
    op.drop_index(op.f('ix_game_starts_at'), table_name='game')
    op.drop_index(op.f('ix_game_stage'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
