"""remove verified field from user table

Revision ID: c7bb94b3352f
Revises: 87aed4bebdcf
Create Date: 2025-07-28 17:08:53.381946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7bb94b3352f'
down_revision = '87aed4bebdcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('verified', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
