"""no name in user table

Revision ID: f30982cc68ae
Revises: b76086a91d21
Create Date: 2025-08-04 17:19:16.136902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30982cc68ae'
down_revision = 'b76086a91d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_name', table_name='user')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    # ### end Alembic commands ###
